name: lithium_bom-dev

services:
  backend:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.lock
        APT_MIRROR: ${APT_MIRROR:-}
        UV_IMAGE: ${UV_IMAGE:-ghcr.io/astral-sh/uv:bookworm-slim}
        DEBIAN_IMAGE: ${DOCKER_REGISTRY_MIRROR:-}debian:bookworm-slim
    volumes:
      - .:/app  # Mount the local project directory to /app in the container
    user: "${USERID}:${GROUPID}"  # Use the host user's UID and GID
    command:
      - "sh"
      - "-c"
      - |
        python -Xfrozen_modules=off /usr/local/lib/python3.14/site-packages/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        manage.py runserver 0.0.0.0:8000 --nothreading --noreload
    ports:
      - 8000:8000
      - 5678:5678
    restart: "no"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: "${DOCKER_REGISTRY_MIRROR:-}postgres:17-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data: