name: lithium_bom-test
services:
  test:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.lock
        APT_MIRROR: ${APT_MIRROR:-}
        UV_IMAGE: ${UV_IMAGE:-ghcr.io/astral-sh/uv:bookworm-slim}
        DEBIAN_IMAGE: ${DOCKER_REGISTRY_MIRROR:-}debian:bookworm-slim
    command: pytest --maxfail=5 --disable-warnings -v
    restart: "no"

volumes:
  postgres_test_data: