[project]
name = "lithium-bom"
version = "v1.4.1"
description = "django app to manage a bill of materials."
authors = [
    { name = "S-Diaco", email = "dyaco8464@yahoo.com" }
]
dependencies = [
    "django>=6.1",
    "django-money>=3.6.1",
    "psycopg2-binary>=2.9.9",
    "gunicorn>=21.2.0",
    "jdatetime>=5.2.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "requests>=2.32.0",
]
readme = "README.md"
requires-python = ">= 3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
managed = true
[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-django>=4.8.0",
    "ruff>=0.3.3",
    "parameterized>=0.9.0",
    "debugpy>=1.8.14",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["django-bom"]

[tool.ruff]
line-length = 120
