# Generated by Django 2.1.5 on 2019-02-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0012_partchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partchangehistory',
            name='part_lookup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bom.Part'),
        ),
    ]
