# Generated by Django 2.1.5 on 2019-02-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0013_partchangehistory_part_lookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partchangehistory',
            name='part_lookup',
        ),
    ]
