# Generated by Django 2.1.5 on 2019-03-02 21:47

from django.db import migrations, models
import django.db.models.deletion


def update_parts_to_part_history(apps, schema_editor):
    Part = apps.get_model('bom', 'Part')
    PartChangeHistory = apps.get_model('bom', 'PartChangeHistory')
    SellerPart = apps.get_model('bom', 'SellerPart')
    Assembly = apps.get_model('bom', 'Assembly')
    Subpart = apps.get_model('bom', 'Subpart')

    for p in Part.objects.all():
        subparts = Subpart.objects.filter(assembly_part=p)
        assembly = None
        if subparts.count() > 0:
            (assembly, created) = Assembly.objects.create()
            for sp in subparts:
                assembly.subparts.add(sp)

        (pch, created) = PartChangeHistory.objects.get_or_create(part=p, description=p.description, revision=p.revision, assembly=assembly)


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0014_auto_20190223_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='partfile',
            name='part',
        ),
        migrations.DeleteModel(
            name='PartFile',
        ),
        migrations.RenameField(
            model_name='partchangehistory',
            old_name='old_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='partchangehistory',
            old_name='old_revision',
            new_name='revision',
        ),
        migrations.RenameField(
            model_name='partchangehistory',
            old_name='attribute_time_stamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='partchangehistory',
            old_name='new_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_number_item',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_number_variation',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_time_stamp',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='original_value',
        ),
        migrations.RunPython(update_parts_to_part_history),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.RemoveField(
            model_name='part',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='part',
            name='subparts',
        ),
        migrations.RemoveField(
            model_name='subpart',
            name='assembly_part',
        ),
        migrations.AlterField(
            model_name='subpart',
            name='assembly_subpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_subpart', to='bom.PartChangeHistory'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='subparts',
            field=models.ManyToManyField(to='bom.Subpart'),
        ),
        migrations.AddField(
            model_name='partchangehistory',
            name='assembly',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bom.Assembly'),
        ),
    ]
