# Generated by Django 2.1.5 on 2019-03-03 19:15

from django.db import migrations, models
import django.db.models.deletion


def update_parts_to_part_history(apps, schema_editor):
    Part = apps.get_model('bom', 'Part')
    PartChangeHistory = apps.get_model('bom', 'PartChangeHistory')
    Assembly = apps.get_model('bom', 'Assembly')
    Subpart = apps.get_model('bom', 'Subpart')

    for p in Part.objects.all():
        subparts = Subpart.objects.filter(assembly_part=p)
        assembly = None
        if subparts.count() > 0:
            assembly = Assembly.objects.create()
            assembly.subparts.set(subparts)

        (pch, created) = PartChangeHistory.objects.get_or_create(part=p, description=p.description,
                                                                 revision=p.revision, assembly=assembly)

    for sp in Subpart.objects.all():
        part = sp.assembly_subpart
        pch = PartChangeHistory.objects.filter(part=part).order_by('-revision').first()
        sp.part_revision = pch
        sp.save()


def update_partchangehistory(apps, schema_editor):
    PartChangeHistory = apps.get_model('bom', 'PartChangeHistory')

    for pch in PartChangeHistory.objects.all():
        pch.description = pch.old_description
        pch.revision = pch.old_revision
        pch.value = pch.new_value
        pch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0014_auto_20190223_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='subparts',
            field=models.ManyToManyField(to='bom.Subpart', related_name='assemblies'),
        ),
        migrations.RemoveField(
            model_name='partfile',
            name='part',
        ),
        migrations.DeleteModel(
            name='PartFile',
        ),
        migrations.RenameField(
            model_name='partchangehistory',
            old_name='attribute_time_stamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='partchangehistory',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='partchangehistory',
            name='revision',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='partchangehistory',
            name='value',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partchangehistory',
            name='attribute',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partchangehistory',
            name='assembly',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='bom.Assembly'),
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='original_value',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_number_item',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_number_variation',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_time_stamp',
        ),
        migrations.RunPython(update_partchangehistory),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_description',
        ),
        migrations.RemoveField(
            model_name='partchangehistory',
            name='old_revision',
        ),
        migrations.AddField(
            model_name='subpart',
            name='part_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assembly_subpart', to='bom.PartChangeHistory'),
        ),
        migrations.RunPython(update_parts_to_part_history),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.RemoveField(
            model_name='part',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='part',
            name='subparts',
        ),
        migrations.RemoveField(
            model_name='subpart',
            name='assembly_part',
        ),
        migrations.RemoveField(
            model_name='subpart',
            name='assembly_subpart',
        ),
    ]
