# Generated by Django 2.2 on 2019-05-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0016_auto_20190405_2308'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='AssemblySubpart',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Assembly')),
                ],
                options={
                    'db_table': 'bom_assembly_subparts',
                },
            ),
            migrations.AlterField(
                model_name='assembly',
                name='subparts',
                field=models.ManyToManyField(through='bom.AssemblySubpart', to='bom.Subpart'),
            ),
            migrations.AddField(
                model_name='assemblysubpart',
                name='assembly',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Assembly'),
            ),
        ])
    ]
