# Generated by Django 2.2 on 2019-06-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0017_auto_20190616_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblySubparts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bom_assembly_subparts',
            },
        ),
        migrations.AlterField(
            model_name='assembly',
            name='subparts',
            field=models.ManyToManyField(related_name='assemblies', through='bom.AssemblySubparts', to='bom.Subpart'),
        ),
        migrations.AddField(
            model_name='assemblysubparts',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Assembly'),
        ),
        migrations.AddField(
            model_name='assemblysubparts',
            name='subpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Subpart'),
        ),
    ]
