# Generated by Django 2.2.2 on 2019-06-27 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0019_auto_20190624_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrevision',
            name='configuration',
            field=models.CharField(choices=[('R', 'Released'), ('W', 'Working')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='partrevision',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='partrevision',
            name='configuration',
            field=models.CharField(choices=[('R', 'Released'), ('W', 'Working')], default='W', max_length=1),
        ),
    ]
