# Generated by Django 2.2.8 on 2019-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0027_auto_20191222_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrevision',
            name='displayable_synopsis',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, null=True),
        ),
    ]
