# Generated by Django 3.2.4 on 2022-05-24 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0043_auto_20211123_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpart',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sellerpart',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='sellerpart',
            unique_together={('seller', 'manufacturer_part', 'minimum_order_quantity', 'unit_cost', 'preferred', 'date')},
        ),
    ]
