# Generated by Django 5.2.8 on 2026-01-08 03:16

from collections import defaultdict

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_unit_definitions(apps, schema_editor):
    QuantityOfMeasure = apps.get_model('bom', 'QuantityOfMeasure')
    UnitDefinition = apps.get_model('bom', 'UnitDefinition')

    # Voltage
    voltage = QuantityOfMeasure.objects.create(name='Voltage')
    UnitDefinition.objects.create(name='Volt', symbol='V', quantity_of_measure=voltage, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Millivolt', symbol='mV', quantity_of_measure=voltage, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Microvolt', symbol='uV', quantity_of_measure=voltage, base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Kilovolt', symbol='kV', quantity_of_measure=voltage, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Megavolt', symbol='MV', quantity_of_measure=voltage, base_multiplier=1000000.0)

    # Current
    current = QuantityOfMeasure.objects.create(name='Current')
    UnitDefinition.objects.create(name='Ampere', symbol='A', quantity_of_measure=current, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Milliampere', symbol='mA', quantity_of_measure=current, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Microampere', symbol='uA', quantity_of_measure=current,
                                  base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Kiloampere', symbol='kA', quantity_of_measure=current, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Megaampere', symbol='MA', quantity_of_measure=current,
                                  base_multiplier=1000000.0)

    # Resistance
    resistance = QuantityOfMeasure.objects.create(name='Resistance')
    UnitDefinition.objects.create(name='Ohm', symbol='Ω', quantity_of_measure=resistance, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Milliohm', symbol='mΩ', quantity_of_measure=resistance, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Kiloohm', symbol='kΩ', quantity_of_measure=resistance, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Megaohm', symbol='MΩ', quantity_of_measure=resistance,
                                  base_multiplier=1000000.0)

    # Capacitance
    capacitance = QuantityOfMeasure.objects.create(name='Capacitance')
    UnitDefinition.objects.create(name='Farad', symbol='F', quantity_of_measure=capacitance, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Millifarad', symbol='mF', quantity_of_measure=capacitance,
                                  base_multiplier=0.001)
    UnitDefinition.objects.create(name='Microfarad', symbol='uF', quantity_of_measure=capacitance,
                                  base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Nanofarad', symbol='nF', quantity_of_measure=capacitance,
                                  base_multiplier=0.000000001)
    UnitDefinition.objects.create(name='Picofarad', symbol='pF', quantity_of_measure=capacitance,
                                  base_multiplier=0.000000000001)

    # Inductance
    inductance = QuantityOfMeasure.objects.create(name='Inductance')
    UnitDefinition.objects.create(name='Henry', symbol='H', quantity_of_measure=inductance, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Millihenry', symbol='mH', quantity_of_measure=inductance, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Microhenry', symbol='uH', quantity_of_measure=inductance,
                                  base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Nanohenry', symbol='nH', quantity_of_measure=inductance,
                                  base_multiplier=0.000000001)

    # Frequency
    frequency = QuantityOfMeasure.objects.create(name='Frequency')
    UnitDefinition.objects.create(name='Hertz', symbol='Hz', quantity_of_measure=frequency, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Kilohertz', symbol='kHz', quantity_of_measure=frequency, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Megahertz', symbol='MHz', quantity_of_measure=frequency,
                                  base_multiplier=1000000.0)
    UnitDefinition.objects.create(name='Gigahertz', symbol='GHz', quantity_of_measure=frequency,
                                  base_multiplier=1000000000.0)

    # Power
    power = QuantityOfMeasure.objects.create(name='Power')
    UnitDefinition.objects.create(name='Watt', symbol='W', quantity_of_measure=power, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Milliwatt', symbol='mW', quantity_of_measure=power, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Microwatt', symbol='uW', quantity_of_measure=power, base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Kilowatt', symbol='kW', quantity_of_measure=power, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Megawatt', symbol='MW', quantity_of_measure=power, base_multiplier=1000000.0)

    # Distance
    distance = QuantityOfMeasure.objects.create(name='Distance')
    UnitDefinition.objects.create(name='Meter', symbol='m', quantity_of_measure=distance, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Centimeter', symbol='cm', quantity_of_measure=distance, base_multiplier=0.01)
    UnitDefinition.objects.create(name='Millimeter', symbol='mm', quantity_of_measure=distance, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Micrometer', symbol='um', quantity_of_measure=distance,
                                  base_multiplier=0.000001)
    UnitDefinition.objects.create(name='Nanometer', symbol='nm', quantity_of_measure=distance,
                                  base_multiplier=0.000000001)
    UnitDefinition.objects.create(name='Kilometer', symbol='km', quantity_of_measure=distance, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Inch', symbol='in', quantity_of_measure=distance, base_multiplier=0.0254)
    UnitDefinition.objects.create(name='Foot', symbol='ft', quantity_of_measure=distance, base_multiplier=0.3048)
    UnitDefinition.objects.create(name='Yard', symbol='yd', quantity_of_measure=distance, base_multiplier=0.9144)
    UnitDefinition.objects.create(name='Mil', symbol='mil', quantity_of_measure=distance, base_multiplier=0.0000254)

    # Weight
    weight = QuantityOfMeasure.objects.create(name='Weight')
    UnitDefinition.objects.create(name='Gram', symbol='g', quantity_of_measure=weight, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Milligram', symbol='mg', quantity_of_measure=weight, base_multiplier=0.001)
    UnitDefinition.objects.create(name='Kilogram', symbol='kg', quantity_of_measure=weight, base_multiplier=1000.0)
    UnitDefinition.objects.create(name='Ounce', symbol='oz', quantity_of_measure=weight, base_multiplier=28.3495)
    UnitDefinition.objects.create(name='Pound', symbol='lb', quantity_of_measure=weight, base_multiplier=453.592)

    # Temperature
    temperature = QuantityOfMeasure.objects.create(name='Temperature')
    UnitDefinition.objects.create(name='Celsius', symbol='C', quantity_of_measure=temperature, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Fahrenheit', symbol='F', quantity_of_measure=temperature, base_multiplier=1.0)

    # Memory
    memory = QuantityOfMeasure.objects.create(name='Memory')
    UnitDefinition.objects.create(name='Byte', symbol='B', quantity_of_measure=memory, base_multiplier=1.0)
    UnitDefinition.objects.create(name='Kilobyte', symbol='KB', quantity_of_measure=memory, base_multiplier=1024.0)
    UnitDefinition.objects.create(name='Megabyte', symbol='MB', quantity_of_measure=memory, base_multiplier=1048576.0)
    UnitDefinition.objects.create(name='Gigabyte', symbol='GB', quantity_of_measure=memory,
                                  base_multiplier=1073741824.0)
    UnitDefinition.objects.create(name='Terabyte', symbol='TB', quantity_of_measure=memory,
                                  base_multiplier=1099511627776.0)


def migrate_part_revision_data(apps, schema_editor):
    PartRevision = apps.get_model('bom', 'PartRevision')
    PartClass = apps.get_model('bom', 'PartClass')
    PartRevisionPropertyDefinition = apps.get_model('bom', 'PartRevisionPropertyDefinition')
    PartRevisionProperty = apps.get_model('bom', 'PartRevisionProperty')
    UnitDefinition = apps.get_model('bom', 'UnitDefinition')
    QuantityOfMeasure = apps.get_model('bom', 'QuantityOfMeasure')

    # Define property definitions
    # Map old field name to (code, name, type, quantity_name)
    field_map = {
        'value': ('value', 'Value', 'string', None),
        'attribute': ('attribute', 'Attribute', 'string', None),
        'pin_count': ('pin_count', 'Pin Count', 'number', None),
        'tolerance': ('tolerance', 'Tolerance', 'string', None),
        'package': ('package', 'Package', 'string', None),
        'material': ('material', 'Material', 'string', None),
        'finish': ('finish', 'Finish', 'string', None),
        'color': ('color', 'Color', 'string', None),
        'length': ('length', 'Length', 'number', 'Distance'),
        'width': ('width', 'Width', 'number', 'Distance'),
        'height': ('height', 'Height', 'number', 'Distance'),
        'weight': ('weight', 'Weight', 'number', 'Weight'),
        'temperature_rating': ('temperature_rating', 'Temperature Rating', 'number', 'Temperature'),
        'temperature_rating_range_max': ('temperature_rating_range_max', 'Temperature Rating Max', 'number',
                                         'Temperature'),
        'temperature_rating_range_min': ('temperature_rating_range_min', 'Temperature Rating Min', 'number',
                                         'Temperature'),
        'wavelength': ('wavelength', 'Wavelength', 'number', 'Distance'),
        'frequency': ('frequency', 'Frequency', 'number', 'Frequency'),
        'memory': ('memory', 'Memory', 'number', 'Memory'),
        'interface': ('interface', 'Interface', 'string', None),
        'power_rating': ('power_rating', 'Power Rating', 'number', 'Power'),
        'supply_voltage': ('supply_voltage', 'Supply Voltage', 'number', 'Voltage'),
        'voltage_rating': ('voltage_rating', 'Voltage Rating', 'number', 'Voltage'),
        'current_rating': ('current_rating', 'Current Rating', 'number', 'Current'),
    }

    # Create definitions
    definitions = {}
    for old_field, (code, name, type_val, quantity_name) in field_map.items():

        # Find the QuantityOfMeasure object if a name is provided
        qom_obj = None
        if quantity_name:
            # We assume these were created in create_unit_definitions
            qom_obj = QuantityOfMeasure.objects.get(name=quantity_name)

        definition, created = PartRevisionPropertyDefinition.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'type': type_val,
                'quantity_of_measure': qom_obj,
                'organization': None
            }
        )
        definitions[old_field] = definition

    # Helper to find unit definition
    unit_cache = {}

    def get_unit(symbol):
        if not symbol:
            return None

        # Handle unicode symbols or mismatches
        symbol_map = {
            '\u03A9': 'Ω',
            'm\u03A9': 'mΩ',
            'k\u03A9': 'kΩ',
            'M\u03A9': 'MΩ',
            '\u03BCF': 'uF',
            '\u03BCV': 'uV',
            '\u03BCA': 'uA',
            '\u00B0C': 'C',
            '\u00B0F': 'F',
            '\u03BCH': 'uH',
            '\u03BCm': 'um',
            '\u212B': 'A',
            '\u03BCW': 'uW',
        }

        mapped_symbol = symbol_map.get(symbol, symbol)

        if mapped_symbol in unit_cache:
            return unit_cache[mapped_symbol]

        try:
            unit = UnitDefinition.objects.get(symbol=mapped_symbol)
            unit_cache[mapped_symbol] = unit
            return unit
        except UnitDefinition.DoesNotExist:
            return None

    # Track needed Class-Definition links: {class_id: [def_id, def_id]}
    class_def_map = defaultdict(set)

    # Iterate over all PartRevisions
    # We use select_related('part') to efficiently access the Part ID and Class ID
    # Note: 'part__number_class' might not be available in migration state directly
    # depending on previous migrations, but accessing .part.number_class_id is safe.
    for pr in PartRevision.objects.select_related('part').iterator():

        # Get the class ID for this part (if it exists)
        # In migration models, foreign keys are usually exposed as ID fields or objects.
        # We try to get the ID safely.
        part_class_id = getattr(pr.part, 'number_class_id', None)

        for old_field, definition in definitions.items():
            val = getattr(pr, old_field, None)

            if val is not None and val != '':

                # 1. RECORD RELATIONSHIP
                if part_class_id:
                    class_def_map[part_class_id].add(definition.id)

                # 2. CREATE PROPERTY (Existing Logic)
                # Check for units
                unit_field = old_field + '_units'
                unit_val = getattr(pr, unit_field, None)

                # Special case for 'value' field which uses 'value_units'
                if old_field == 'value':
                    unit_val = getattr(pr, 'value_units', None)

                unit_ref = get_unit(unit_val)

                # Create Property
                prop = PartRevisionProperty(
                    part_revision=pr,
                    property_definition=definition,
                    value_raw=str(val),
                    unit_definition=unit_ref
                )

                # Calculate normalized value
                if unit_ref and val:
                    try:
                        float_val = float(val)
                        prop.value_normalized = float_val * unit_ref.base_multiplier
                    except (ValueError, TypeError):
                        pass

                prop.save()

    # Apply the Class -> Definition links
    for class_id, def_ids in class_def_map.items():
        try:
            pc = PartClass.objects.get(id=class_id)
            # We can pass multiple IDs to .add()
            pc.property_definitions.add(*def_ids)
        except PartClass.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('bom', '0051_alter_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Voltage', max_length=64)),
                ('organization',
                 models.ForeignKey(blank=True, help_text='Leave empty for a Global/System record.', null=True,
                                   on_delete=django.db.models.deletion.CASCADE, to=settings.BOM_ORGANIZATION_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartRevisionPropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('R', 'String'), ('W', 'Float'), ('B', 'Boolean')], max_length=1)),
                ('required', models.BooleanField(default=False)),
                ('organization',
                 models.ForeignKey(blank=True, help_text='Leave empty for a Global/System record.', null=True,
                                   on_delete=django.db.models.deletion.CASCADE, to=settings.BOM_ORGANIZATION_MODEL)),
                ('quantity_of_measure', models.ForeignKey(blank=True,
                                                          help_text='If set, this property is numeric and restricted to units of this quantity.',
                                                          null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                          to='bom.quantityofmeasure')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UnitDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=16)),
                ('base_multiplier', models.FloatField(default=1.0)),
                ('organization',
                 models.ForeignKey(blank=True, help_text='Leave empty for a Global/System record.', null=True,
                                   on_delete=django.db.models.deletion.CASCADE, to=settings.BOM_ORGANIZATION_MODEL)),
                ('quantity_of_measure',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units',
                                   to='bom.quantityofmeasure')),
            ],
            options={
                'ordering': ['base_multiplier'],
                'unique_together': {('organization', 'quantity_of_measure', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='PartRevisionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_raw', models.CharField(max_length=255)),
                ('value_normalized', models.FloatField(blank=True, null=True)),
                ('part_revision',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties',
                                   to='bom.partrevision')),
                ('property_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          to='bom.partrevisionpropertydefinition')),
                ('unit_definition',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='bom.unitdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='partclass',
            name='property_definitions',
            field=models.ManyToManyField(blank=True, related_name='part_classes',
                                         to='bom.partrevisionpropertydefinition'),
        ),

        migrations.RunPython(create_unit_definitions),
        migrations.RunPython(migrate_part_revision_data),

        migrations.RemoveField(
            model_name='partrevision',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='color',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='current_rating',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='current_rating_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='frequency_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='height',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='height_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='length',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='length_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='material',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='memory_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='package',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='pin_count',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='power_rating',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='power_rating_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='supply_voltage',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='supply_voltage_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='temperature_rating',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='temperature_rating_range_max',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='temperature_rating_range_min',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='temperature_rating_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='tolerance',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='value',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='value_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='voltage_rating',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='voltage_rating_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='wavelength',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='wavelength_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='weight_units',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='width',
        ),
        migrations.RemoveField(
            model_name='partrevision',
            name='width_units',
        ),
    ]