# Generated by Django 6.1 on 2026-08-23 15:53

import bom.base_classes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0052_alter_manufacturer_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("contact_name", models.CharField(blank=True, default="", max_length=128)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("address", models.TextField(blank=True, default="")),
                ("tax_id", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bom.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
            bases=(models.Model, bom.base_classes.AsDictModel),
        ),
        migrations.CreateModel(
            name="CustomerPrice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                (
                    "base_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        default="USD", editable=False, max_length=3
                    ),
                ),
                (
                    "base_cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=0, default_currency="USD", max_digits=19
                    ),
                ),
                (
                    "profit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        default="USD", editable=False, max_length=3
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=0, default_currency="USD", max_digits=19
                    ),
                ),
                ("is_manual_price", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="bom.customer",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_prices",
                        to="bom.part",
                    ),
                ),
                (
                    "part_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_prices",
                        to="bom.partrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
            bases=(models.Model, bom.base_classes.AsDictModel),
        ),
        migrations.AddIndex(
            model_name="customerprice",
            index=models.Index(
                fields=["customer", "part", "-created_at"],
                name="bom_cprice_cust_part_created",
            ),
        ),
    ]
