# Generated by Django 6.0.2 on 2026-02-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0053_alter_partrevision_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Editor'), ('V', 'Viewer')], max_length=1),
        ),
    ]
