# Generated by Django 6.0.2 on 2026-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0054_alter_usermeta_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Probation / Unassessed'), ('A', 'Approved'), ('R', 'Restricted / Do Not Use')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Probation / Unassessed'), ('A', 'Approved'), ('R', 'Restricted / Do Not Use')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
