# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0054_customer_pricing_state_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeta",
            name="calendar",
            field=models.CharField(
                choices=[("J", "Jalali"), ("G", "Gregorian")],
                default="J",
                max_length=1,
            ),
        ),
    ]
