# Generated by Django 6.0.4 on 2026-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0056_rename_sourcing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sourcing_provider',
            field=models.CharField(blank=True, choices=[('mouser', 'Mouser'), ('nexar', 'Nexar')], default='nexar', max_length=32),
        ),
    ]
