# Generated by Django 6.0.4 on 2026-06-04 14:02

import bom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0057_organization_sourcing_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sourcing_api_key',
            field=bom.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sourcing_api_secret',
            field=bom.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
