# Generated by Django 6.0.4 on 2026-06-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0058_organization_sourcing_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerpart',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
