# Generated by Django 6.0.4 on 2026-06-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0059_manufacturerpart_datasheet_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sourcing_provider',
            field=models.CharField(blank=True, choices=[('mouser', 'Mouser'), ('nexar', 'Nexar')], default='mouser', max_length=32),
        ),
    ]
