# Generated by Django 6.0.4 on 2026-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0060_alter_organization_sourcing_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sourcing_provider',
            field=models.CharField(blank=True, choices=[('mouser', 'Mouser'), ('nexar', 'Nexar')], default='nexar', max_length=32),
        ),
    ]
