# Generated by Django 6.0.4 on 2026-07-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0061_alter_organization_sourcing_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, help_text='A picture to help identify this part.', null=True, upload_to='part_images/'),
        ),
    ]
