# Generated by Django 6.0.4 on 2026-07-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0062_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sourcing_provider',
            field=models.CharField(blank=True, choices=[('mouser', 'Mouser'), ('nexar', 'Octopart')], default='nexar', max_length=32),
        ),
    ]
